model_list:
  - model_name: cheap-coder
    litellm_params:
      model: groq/qwen/qwen3-32b
      api_key: os.environ/GROQ_API_KEY
  - model_name: cheap-coder
    litellm_params:
      model: groq/moonshotai/kimi-k2-instruct
      api_key: os.environ/GROQ_API_KEY
  - model_name: cheap-coder
    litellm_params:
      model: groq/meta-llama/llama-4-scout-17b-16e-instruct
      api_key: os.environ/GROQ_API_KEY

litellm_settings:
  fallbacks: [{"cheap-coder": ["cheap-coder"]}]
  num_retries: 0
